from django.conf import settings


RESOURCES_DEFAULT_DISK_MAX_REQ = getattr(settings, 'RESOURCES_DEFAULT_DISK_MAX_REQ', 1000)
RESOURCES_DEFAULT_DISK_DFLT_REQ = getattr(settings, 'RESOURCES_DEFAULT_DISK_DFLT_REQ', 200)


RESOURCES_DEFAULT_MEMORY_MAX_REQ = getattr(settings, 'RESOURCES_DEFAULT_MEMORY_MAX_REQ', 2048)
RESOURCES_DEFAULT_MEMORY_DFLT_REQ = getattr(settings, 'RESOURCES_DEFAULT_MEMORY_DFLT_REQ', 512)


RESOURCES_DEFAULT_PUB4_MAX_REQ = getattr(settings, 'RESOURCES_DEFAULT_PUB4_MAX_REQ', 1)
RESOURCES_DEFAULT_PUB4_DFLT_REQ = getattr(settings, 'RESOURCES_DEFAULT_PUB4_DFLT_REQ', 0)


RESOURCES_DEFAULT_PUB6_MAX_REQ = getattr(settings, 'RESOURCES_DEFAULT_PUB6_MAX_REQ', 0)
RESOURCES_DEFAULT_PUB6_DFLT_REQ = getattr(settings, 'RESOURCES_DEFAULT_PUB6_DFLT_REQ', 0)
