from django.conf import settings


RESOURCES_DEFAULT_DISK_MAX_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_DISK_MAX_SLIVER', 1000)
RESOURCES_DEFAULT_DISK_DFLT_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_DISK_DFLT_SLIVER', 200)


RESOURCES_DEFAULT_PUB4_MAX_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_PUB4_MAX_SLIVER', 0)
RESOURCES_DEFAULT_PUB4_DFLT_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_PUB4_DFLT_SLIVER', 0)


RESOURCES_DEFAULT_PUB6_MAX_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_PUB6_MAX_SLIVER', 0)
RESOURCES_DEFAULT_PUB6_DFLT_SLIVER = getattr(settings, 'RESOURCES_DEFAULT_PUB6_DFLT_SLIVER', 0)


