from django.conf.urls import patterns, include, url
from nodes import views as node_views
urlpatterns = patterns('',
                       url(r'^$',
                           node_views.index,
                           name="index"),
                       url(r'^node_index/$',
                           node_views.node_index,
                           name="node_index"),
                       url(r'^create_slice/$',
                           node_views.create_slice,
                           name="create_slice"),
                       url(r'^show_own_slices/$',
                           node_views.show_own_slices,
                           name="show_own_slices"),

                       url(r'^upload_node/$',
                           node_views.upload_node,
                           name="upload_node"),
                       url(r'^edit_node/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.edit_node,
                           name="edit_node"),
                       url(r'^delete_node/$',
                           node_views.delete_node,
                           name="delete_node"),
                       url(r'^get_node_configuration/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.get_node_configuration,
                           name="get_node_configuration"),
                       url(r'^get_node_public_keys/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.get_node_public_keys,
                           name="get_node_public_keys"),
                       url(r'^get_slice_public_keys/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.get_slice_public_keys,
                           name="get_slice_public_keys"),
                       url(r'^deploy_slivers/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.deploy_slivers,
                           name="deploy_slivers"),
                       url(r'^start_sliver/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.start_sliver,
                           name="start_sliver"),
                       url(r'^stop_sliver/html/([a-zA-Z0-9\-\_\.\,]+)/$',
                           node_views.stop_sliver,
                           name="stop_sliver"),

                       # XML

                       url(r'^upload_node/xml/$',
                           node_views.upload_node_xml,
                           name="upload_node_xml"),
                       url(r'^delete_node/xml/$',
                           node_views.delete_node_xml,
                           name="delete_node_xml"),
                       url(r'^get_node_configuration/xml/$',
                           node_views.get_node_configuration_xml,
                           name="get_node_configuration_xml"),
                       url(r'^get_node_public_keys/xml/$',
                           node_views.get_node_public_keys_xml,
                           name="get_node_public_keys_xml"),

                       )
